from GBcrawler import GBcrawler


geneInfo = GBcrawler("tth1.gb")
print("------LOADING EXAMPLE------")
print ("file name:" + geneInfo.filename + "\n")
print ("sequence: " + geneInfo.sequenceID)
print ("lenght:" + geneInfo.sequenceLength)
print ("molecule: " + geneInfo.strand+geneInfo.moleculeType)
print ("division: "+geneInfo.division)
print ("moification date: "+ geneInfo.modDate)
print("------DEFINITION------")
print (geneInfo.definition)
print("------ACCESSION------")
print (geneInfo.accession)
print("------VERSION------")
print (geneInfo.version)
print("------KEYWORDS------")
print (geneInfo.keywords)
print("------Comment------")
print (geneInfo.comment)
print("------SEQUENCE------")
#print (''.join(geneInfo.sequence))
print (len(geneInfo.sequenceList))
print (geneInfo.baseCount)
print (geneInfo)
#print (geneInfo.featureList)
for i in geneInfo.featureList:
	print(i.type)
print (len(geneInfo.featureList))
#print (geneInfo.featureList[0].name)
#print (geneInfo.featureList[0].begin)
#print (geneInfo.featureList[0].end)
#print (geneInfo.referenceList)